RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 6
CHUNK_SIZE: 500
CHUNK_OVERLAP: 50
DATA_PATH: '/Users/bdbrodie/dev/altinn/docs/content/'
DB_FAISS_PATH: 'docs_qa/vectorstore/db_faiss'
# MODEL_TYPE: 'mpt'
# MODEL_BIN_PATH: 'models/mpt-7b-instruct.ggmlv3.q8_0.bin'
MODEL_TYPE: 'gpt-4'
MODEL_BIN_PATH: ''
MAX_NEW_TOKENS: 1000
TEMPERATURE: 1.0
MAX_CONTEXT_LENGTH: 40000
MAX_SOURCE_LENGTH: 10000
MAX_CONTEXT_DOC_COUNT: 10
TYPESENSE_CONFIG:
  nodes:
  - host: 'u4zlso3dx2vtip6jp-1.a1.typesense.net'
    port: '443'
    protocol: 'https'
  connection_timeout_seconds': 2
DOCS_COLLECTION: 'altinn-studio-docs'
DOCS_SEARCH_PHRASE_COLLECTION: 'altinn-studio-docs-search-phrases'
