RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 6
CHUNK_SIZE: 500
CHUNK_OVERLAP: 50
DATA_PATH: '/Users/bdbrodie/dev/altinn/docs/content/'
DB_FAISS_PATH: 'docs_qa/vectorstore/db_faiss'
# MODEL_TYPE: 'mpt'
# MODEL_BIN_PATH: 'models/mpt-7b-instruct.ggmlv3.q8_0.bin'
MODEL_TYPE: 'gpt-4-1106-preview'
MODEL_BIN_PATH: ''
MAX_NEW_TOKENS: 1000
TEMPERATURE: 1.0
MAX_CONTEXT_LENGTH: 40000
MAX_SOURCE_LENGTH: 4000
TYPESENSE_CONFIG:
  nodes:
  - host: 'altinn-typesense-api.azurewebsites.net'
    port: '443'
    protocol: 'https'
  api_key: 'xyx'
  connection_timeout_seconds': 2
