GH_Altinn/altinn-studio_ISSUES_SYNC_UPDATED_AT: 1700653471
GH_Altinn/app-frontend-react_ISSUES_SYNC_UPDATED_AT: 1700648576
GH_Altinn/app-lib-dotnet_ISSUES_SYNC_UPDATED_AT: 1700653859
GH_Altinn/app-template-dotnet_ISSUES_SYNC_UPDATED_AT: 1700650416
GH_REPO_LIST: Altinn/altinn-studio,Altinn/app-frontend-react,Altinn/app-lib-dotnet,Altinn/app-template-dotnet
MAX_CONTEXT_LENGTH: 9000
MAX_SOURCE_LENGTH: 4000
MODEL_TYPE: gpt-4-1106-preview
TYPESENSE_CONFIG:
  api_key: xyx
  connection_timeout_seconds: 200
  nodes:
  - host: altinn-typesense-api.azurewebsites.net
    port: '443'
    protocol: https
