GH_Altinn/altinn-studio_ISSUES_SYNC_UPDATED_AT: 1699881589
GH_REPO_LIST: Altinn/altinn-studio,Altinn/app-frontend-react
TYPESENSE_CONFIG:
  api_key: xyx
  connection_timeout_seconds': 200
  nodes:
  - host: altinn-typesense-api.azurewebsites.net
    port: '443'
    protocol: https
