MAX_CONTEXT_LENGTH: 40000
MAX_SOURCE_LENGTH: 10000
MAX_CONTEXT_DOC_COUNT: 10
TYPESENSE_CONFIG:
  nodes:
  - host: 'u4zlso3dx2vtip6jp-1.a1.typesense.net'
    port: '443'
    protocol: 'https'
  connection_timeout_seconds': 2
