RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 2
CHUNK_SIZE: 500
CHUNK_OVERLAP: 50
DATA_PATH: '/Users/bdbrodie/dev/altinn/docs/content/community/devops/teams/'
DB_FAISS_PATH: 'vectorstore/db_faiss'
# MODEL_TYPE: 'mpt'
# MODEL_BIN_PATH: 'models/mpt-7b-instruct.ggmlv3.q8_0.bin'
MODEL_TYPE: 'gpt-4'
MODEL_BIN_PATH: '../models/llama-2-7b-chat.ggmlv3.q8_0.bin'
MAX_NEW_TOKENS: 512
TEMPERATURE: 0.01