name: Trigger auto deployment for digdir-slack-bot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ docker ]
    paths:
    - '**'
    - '.github/workflows/digdir-slack-bot-AutoDeployTrigger-f91f9261-5791-4778-a015-f55d5e2a578d.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DIGDIRSLACKBOT_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: altinnaicontainers.azurecr.io
          registryUsername: ${{ secrets.DIGDIRSLACKBOT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DIGDIRSLACKBOT_REGISTRY_PASSWORD }}
          containerAppName: digdir-slack-bot
          resourceGroup: altinn-ai-assistant
          imageToBuild: altinnaicontainers.azurecr.io/altinn-assistant:${{ github.sha }}
          
            

     

